// Generates src/contract.gen.ts from the contract JSON Schema that
// mailune-protocol commits as an insta snapshot, so the web types are never
// written by hand. Run `npm run contract` after that snapshot changes; a
// vitest fails while the two disagree.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { compile, type JSONSchema } from "json-schema-to-typescript";

const SNAPSHOT = new URL(
  "../../crates/mailune-protocol/src/snapshots/mailune_protocol__tests__contract_json_schema_matches_the_snapshot.snap",
  import.meta.url,
);
const OUTPUT = new URL("../src/contract.gen.ts", import.meta.url);
const ROOTS = ["Envelope", "Event", "Submission"] as const;

type Schema = JSONSchema & { $defs?: Record<string, JSONSchema> };

/** The schemas in the snapshot, keyed by root type name. */
export function contractSchemas(): Record<(typeof ROOTS)[number], Schema> {
  const text = readFileSync(SNAPSHOT, "utf8");
  // insta puts a YAML header between two `---` lines before the value.
  const body = text.replace(/^---\n[\s\S]*?\n---\n/, "");
  return JSON.parse(body) as Record<(typeof ROOTS)[number], Schema>;
}

/**
 * Drops the keywords schemars writes next to a `$ref` (a field description).
 * The generator turns a `$ref` with siblings into a fresh copy of the type
 * (`Address1`, `Flags1`), which would not be assignable across fields.
 */
function bareRefs(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(bareRefs);
  }
  if (typeof value !== "object" || value === null) {
    return value;
  }
  const record = value as Record<string, unknown>;
  if (typeof record.$ref === "string") {
    return { $ref: record.$ref };
  }
  return Object.fromEntries(Object.entries(record).map(([key, inner]) => [key, bareRefs(inner)]));
}

/** One schema whose `$defs` hold every root and every shared definition. */
export function mergedSchema(): Schema {
  const schemas = contractSchemas();
  const defs: Record<string, JSONSchema> = {};
  const add = (name: string, schema: JSONSchema) => {
    const known = defs[name];
    // Each root repeats the definitions it uses; one name with two shapes
    // would make the generated type wrong for one of them.
    if (known && JSON.stringify(known) !== JSON.stringify({ ...schema, title: name })) {
      throw new Error(`contract definition ${name} has two shapes`);
    }
    // Without a title the generator names a type after the first path that
    // reaches it, and a second path yields a copy (`Address1`).
    defs[name] = { ...schema, title: name };
  };
  for (const root of ROOTS) {
    const { $defs, $schema: _schema, ...rest } = schemas[root];
    for (const [name, schema] of Object.entries($defs ?? {})) {
      add(name, schema);
    }
    add(root, rest);
  }
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Contract",
    type: "object",
    properties: Object.fromEntries(ROOTS.map((root) => [root, { $ref: `#/$defs/${root}` }])),
    required: [...ROOTS],
    $defs: defs,
  };
}

/** The text of src/contract.gen.ts. */
export async function renderContract(): Promise<string> {
  return compile(bareRefs(mergedSchema()) as JSONSchema, "Contract", {
    additionalProperties: false,
    bannerComment:
      "// Generated by web/scripts/contract.ts from the mailune-protocol contract schema. Do not edit.",
    unreachableDefinitions: true,
  });
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(OUTPUT, await renderContract());
}
