/*
 * Generated by cbindgen from crates/mailune-capi/src/abi.rs:
 * `MAILUNE_BLESS=1 cargo nextest run -p mailune-capi`. Do not edit.
 */

#ifndef MAILUNE_H
#define MAILUNE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// The view models one shell window renders. Safe to use from several
// threads at once.
typedef struct MailuneCore MailuneCore;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The version of the core this library was built from. `ok`: a string.
char *mailune_version(void);

// Free an answer from any function in this library. NULL is ignored.
//
// # Safety
//
// `answer` is NULL or a string this library returned, not yet freed.
void mailune_string_free(char *answer);

// A new core: empty list, no open thread, empty draft, English on the free
// plan. Free it with `mailune_core_free`.
struct MailuneCore *mailune_core_new(void);

// Free a core from `mailune_core_new`. NULL is ignored.
//
// # Safety
//
// `core` came from `mailune_core_new`, is not freed yet, and no call is
// using it.
void mailune_core_free(struct MailuneCore *core);

// Apply `events`, a JSON array of `Event`, in order. `ok`: the `ViewState`
// to render.
//
// # Safety
//
// `core` came from `mailune_core_new` and is not freed yet; `events` is a
// NUL-terminated string.
char *mailune_core_fold(const struct MailuneCore *core, const char *events);

// The state to render now. `ok`: a `ViewState`.
//
// # Safety
//
// `core` came from `mailune_core_new` and is not freed yet.
char *mailune_core_state(const struct MailuneCore *core);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MAILUNE_H */
