/*
 * Generated by cbindgen from crates/mailune-capi/src/lib.rs.
 * Do not edit.
 */

#ifndef MAILUNE_H
#define MAILUNE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Confirms the domain is linked. `ok` is null.
char *mailune_ready(void);

// Parses a search query. `ok` is `{"terms": [...]}`.
//
// # Safety
//
// `query` is a NUL-terminated UTF-8 string valid for this call, or the
// function returns an error record.
char *mailune_parse_query(const char *query);

// Frees an answer from this library. NULL is ignored.
//
// # Safety
//
// `answer` is NULL or a pointer returned by this library and not yet freed.
void mailune_string_free(char *answer);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MAILUNE_H */
