//! UniFFI surface for native shells.
//!
//! Each `#[uniffi::export]` forwards one call into [`api`]. The scaffolding
//! is generated by uniffi 0.32; this crate does not open a socket or a keychain.

mod api;

uniffi::setup_scaffolding!();

/// One thread the shell can show. UI chrome stays on the Swift side.
#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct ThreadRecord {
    /// Provider conversation id.
    pub id: String,
    /// Subject line.
    pub subject: String,
    /// The row is unread.
    pub unread: bool,
}

/// Why a forwarded call failed. The text is safe to show.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum FfiError {
    /// [`mailune_protocol::ready`] failed.
    #[error("the core is not ready: {message}")]
    NotReady {
        /// What the contract reported.
        message: String,
    },
}

/// Receives thread records. Implemented by the shell.
#[uniffi::export(callback_interface)]
pub trait ThreadSink {
    /// The latest rows, in list order.
    fn on_threads(&self, threads: Vec<ThreadRecord>);
}

/// Confirms the contract crate linked. The future finishes immediately.
#[uniffi::export]
pub async fn core_ready() -> Result<(), FfiError> {
    api::core_ready().await
}

/// Delivers `threads` through `sink`.
#[uniffi::export]
pub fn publish_threads(threads: Vec<ThreadRecord>, sink: Box<dyn ThreadSink>) {
    api::publish_threads(threads, sink)
}

#[cfg(test)]
mod tests {
    use std::sync::{Arc, Mutex};

    use super::{ThreadRecord, ThreadSink, publish_threads};

    struct Collect(Arc<Mutex<Vec<ThreadRecord>>>);

    impl ThreadSink for Collect {
        fn on_threads(&self, threads: Vec<ThreadRecord>) {
            *self.0.lock().expect("lock") = threads;
        }
    }

    #[test]
    fn core_ready_forwards_to_the_protocol() {
        let ready = super::core_ready();
        let mut future = std::pin::pin!(ready);
        let waker = std::task::Waker::noop();
        let mut context = std::task::Context::from_waker(waker);
        match future.as_mut().poll(&mut context) {
            std::task::Poll::Ready(result) => assert!(result.is_ok()),
            std::task::Poll::Pending => panic!("ready finishes immediately"),
        }
    }

    #[test]
    fn a_row_becomes_a_record_and_the_callback_receives_it() {
        let records = vec![ThreadRecord {
            id: "t1".to_string(),
            subject: "Hello".to_string(),
            unread: true,
        }];
        let seen = Arc::new(Mutex::new(Vec::new()));
        publish_threads(records.clone(), Box::new(Collect(seen.clone())));
        assert_eq!(seen.lock().expect("lock").len(), 1);
    }
}
