[package]
name = "mailune-mime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "MIME parse and build"

[dependencies]
ammonia = { workspace = true }
base64 = { workspace = true }
encoding_rs = { workspace = true }
html2text = { workspace = true }
icalendar = { workspace = true }
mail-builder = { workspace = true }
mail-parser = { workspace = true }
mailune-protocol = { path = "../mailune-protocol" }
rsa = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[lints]
workspace = true
