//! C ABI for front ends that load a shared library.
//!
//! Records cross as JSON strings, not C structs. Each export forwards one
//! call. The answer is allocated with the Rust allocator and released with
//! [`mailune_string_free`]. `include/mailune.h` is generated by cbindgen; the
//! test fails when that file drifts.

use std::ffi::{CStr, CString, c_char};

use mailune_core::{Query, Term};
use serde_json::{Value, json};

/// Failure of one C call. The message names the problem, not the query bytes.
#[derive(Debug, thiserror::Error)]
enum Error {
    /// `mailune-core` rejected the call.
    #[error(transparent)]
    Core(#[from] mailune_core::Error),
    /// The pointer was null or the bytes were not UTF-8.
    #[error("argument is not a UTF-8 string")]
    Argument,
}

/// `{"ok": ...}` or `{"error": {"message": ...}}`.
fn envelope(result: Result<Value, Error>) -> String {
    let body = match result {
        Ok(value) => json!({"ok": value}),
        Err(error) => json!({"error": {"message": error.to_string()}}),
    };
    body.to_string()
}

fn term_record(term: &Term) -> Value {
    match term {
        Term::From(value) => json!({"kind": "from", "value": value}),
        Term::To(value) => json!({"kind": "to", "value": value}),
        Term::HasAttachment => json!({"kind": "has", "value": "attachment"}),
        Term::Before(date) => json!({
            "kind": "before",
            "year": date.year,
            "month": date.month,
            "day": date.day,
        }),
        Term::Unread => json!({"kind": "is", "value": "unread"}),
        Term::Label(value) => json!({"kind": "label", "value": value}),
        Term::Text(value) => json!({"kind": "text", "value": value}),
    }
}

fn query_record(query: &Query) -> Value {
    json!({
        "terms": query.terms.iter().map(term_record).collect::<Vec<_>>(),
    })
}

/// Copies `json` into a C string. NULL when the text contains an interior NUL.
fn owned_json(json: String) -> *mut c_char {
    CString::new(json).map_or(std::ptr::null_mut(), CString::into_raw)
}

#[allow(unsafe_code)]
fn read_text(ptr: *const c_char) -> Result<String, Error> {
    if ptr.is_null() {
        return Err(Error::Argument);
    }
    // SAFETY: the caller promised a NUL-terminated string that outlives this call.
    let text = unsafe { CStr::from_ptr(ptr) };
    text.to_str()
        .map(str::to_owned)
        .map_err(|_| Error::Argument)
}

fn forward_ready() -> *mut c_char {
    let result = mailune_core::ready().map(|()| Value::Null);
    owned_json(envelope(result.map_err(Error::from)))
}

fn forward_parse_query(query: *const c_char) -> *mut c_char {
    let result = read_text(query).and_then(|text| {
        mailune_core::parse_query(&text)
            .map(|parsed| query_record(&parsed))
            .map_err(Error::from)
    });
    owned_json(envelope(result))
}

#[allow(unsafe_code)]
fn free_answer(answer: *mut c_char) {
    if answer.is_null() {
        return;
    }
    // SAFETY: `answer` came from `CString::into_raw` in this crate and is not freed yet.
    unsafe { drop(CString::from_raw(answer)) }
}

/// Confirms the domain is linked. `ok` is null.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub extern "C" fn mailune_ready() -> *mut c_char {
    forward_ready()
}

/// Parses a search query. `ok` is `{"terms": [...]}`.
///
/// # Safety
///
/// `query` is a NUL-terminated UTF-8 string valid for this call, or the
/// function returns an error record.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn mailune_parse_query(query: *const c_char) -> *mut c_char {
    forward_parse_query(query)
}

/// Frees an answer from this library. NULL is ignored.
///
/// # Safety
///
/// `answer` is NULL or a pointer returned by this library and not yet freed.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn mailune_string_free(answer: *mut c_char) {
    free_answer(answer);
}

#[cfg(test)]
#[allow(unsafe_code)]
mod tests {
    use std::ffi::{CStr, CString, c_char};
    use std::path::PathBuf;

    use super::{mailune_parse_query, mailune_ready, mailune_string_free};

    fn crate_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
    }

    fn take(ptr: *mut c_char) -> String {
        assert!(!ptr.is_null());
        // SAFETY: `ptr` came from this crate and has not been freed.
        let text = unsafe { CStr::from_ptr(ptr) }.to_str().unwrap().to_owned();
        // SAFETY: the same pointer, freed once.
        unsafe { mailune_string_free(ptr) };
        text
    }

    fn check_drift(relative: &str, rendered: &str) {
        let path = crate_dir().join(relative);
        if std::env::var_os("MAILUNE_BLESS").is_some() {
            std::fs::write(&path, rendered).unwrap();
            return;
        }
        let committed = std::fs::read_to_string(&path)
            .unwrap_or_default()
            .replace("\r\n", "\n");
        assert!(
            committed == rendered.replace("\r\n", "\n"),
            "{relative} is stale: run MAILUNE_BLESS=1 cargo nextest run -p mailune-capi"
        );
    }

    #[test]
    fn ready_and_a_query_are_json_records() {
        let ready = take(mailune_ready());
        assert_eq!(ready, r#"{"ok":null}"#);
        let query = CString::new("from:ada hello").unwrap();
        // SAFETY: `query` is a live NUL-terminated string.
        let parsed = take(unsafe { mailune_parse_query(query.as_ptr()) });
        assert_eq!(
            parsed,
            r#"{"ok":{"terms":[{"kind":"from","value":"ada"},{"kind":"text","value":"hello"}]}}"#
        );
    }

    #[test]
    fn a_null_or_bad_query_is_an_error_record() {
        // SAFETY: NULL is the argument under test.
        let missing = take(unsafe { mailune_parse_query(std::ptr::null()) });
        assert_eq!(
            missing,
            r#"{"error":{"message":"argument is not a UTF-8 string"}}"#
        );
        let query = CString::new("foo:bar").unwrap();
        // SAFETY: `query` is a live NUL-terminated string.
        let bad = take(unsafe { mailune_parse_query(query.as_ptr()) });
        assert!(
            bad.starts_with(r#"{"error":{"message":"bad search token:"#),
            "{bad}"
        );
        // SAFETY: NULL is ignored.
        unsafe { mailune_string_free(std::ptr::null_mut()) };
    }

    #[test]
    fn the_committed_header_is_what_cbindgen_generates() {
        let config = cbindgen::Config::from_file(crate_dir().join("cbindgen.toml")).unwrap();
        let mut bytes = Vec::new();
        cbindgen::Builder::new()
            .with_config(config)
            .with_crate(crate_dir())
            .generate()
            .unwrap()
            .write(&mut bytes);
        let rendered = String::from_utf8(bytes).unwrap();
        check_drift("include/mailune.h", &rendered);
        let vapi = std::fs::read_to_string(crate_dir().join("vapi/mailune.vapi")).unwrap();
        let meson = std::fs::read_to_string(crate_dir().join("meson.build")).unwrap();
        for name in [
            "mailune_ready",
            "mailune_parse_query",
            "mailune_string_free",
        ] {
            assert!(rendered.contains(name), "{name} missing from the header");
            if name != "mailune_string_free" {
                assert!(vapi.contains(name), "{name} missing from the vapi");
            }
        }
        assert!(vapi.contains("mailune_string_free"));
        assert!(meson.contains("mailune_capi"));
        assert!(meson.contains("mailune.vapi"));
    }
}
