// swift-tools-version: 6.0

import PackageDescription

let package = Package(
    name: "MailuneUI",
    defaultLocalization: "en",
    platforms: [.macOS("26.0")],
    products: [
        .library(name: "MailuneUI", targets: ["MailuneUI"])
    ],
    dependencies: [
        .package(path: "../MailuneModel"),
    ],
    targets: [
        .target(
            name: "MailuneUI",
            dependencies: ["MailuneModel"],
            // Generated by scripts/catalogs.sh from i18n/; run it before building.
            resources: [.process("Catalogs")]
        ),
        .testTarget(name: "MailuneUITests", dependencies: ["MailuneUI"]),
    ]
)
