<Project Sdk="MSTest.Sdk/4.4.1">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Mailune.AppCore/Mailune.AppCore.csproj" />
    <None Include="../Mailune.App/Tokens.xaml" Link="Tokens.xaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
