// Generated by web/scripts/contract.ts from the mailune-protocol contract schema. Do not edit.

/**
 * One message.
 *
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "MessageId".
 */
export type MessageId = string;
/**
 * One conversation, as the provider or the threading engine names it.
 *
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "ThreadId".
 */
export type ThreadId = string;
/**
 * How the message travelled. End-to-end crypto is a later crate.
 *
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "TransportSecurity".
 */
export type TransportSecurity = "clear" | "tls";
/**
 * A fact the UI renders. Surfaces do not invent these.
 *
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Event".
 */
export type Event =
  | {
      notice: {
        /**
         * Text the UI can show. Not a message body.
         */
        message: string;
      };
    }
  | {
      snapshot: {
        /**
         * Rows in list order.
         */
        threads: ThreadRow[];
      };
    };
/**
 * One mail account.
 *
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "AccountId".
 */
export type AccountId = string;
/**
 * Triage tab. The mock stores `cat` as `0` Primary, `1` Social,
 * `2` Promotions, `3` Updates.
 *
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Category".
 */
export type Category = "primary" | "social" | "promotions" | "updates";
/**
 * One mailbox, special-use or user-created.
 *
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "MailboxId".
 */
export type MailboxId = string;
/**
 * A typed request from a surface. The core applies it; the model only
 * proposes values of this enum.
 *
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Submission".
 */
export type Submission =
  | "refresh"
  | {
      open_thread: {
        thread: ThreadId;
      };
    }
  | {
      send: {
        /**
         * Plain body. Rich MIME is built by the MIME crate.
         */
        body: string;
        /**
         * Subject line.
         */
        subject: string;
        /**
         * Recipients.
         */
        to: Address[];
      };
    }
  | {
      save_draft: {
        /**
         * Plain body.
         */
        body: string;
        /**
         * Subject line.
         */
        subject: string;
        /**
         * Recipients so far.
         */
        to: Address[];
      };
    }
  | {
      archive: {
        /**
         * Conversations to archive.
         */
        threads: ThreadId[];
      };
    }
  | {
      delete: {
        /**
         * Conversations to delete.
         */
        threads: ThreadId[];
      };
    }
  | {
      spam: {
        /**
         * Conversations to mark.
         */
        threads: ThreadId[];
      };
    }
  | {
      snooze: {
        /**
         * The mock passes the preset as a string the UI already chose.
         */
        preset: string;
        thread: ThreadId;
      };
    }
  | {
      move_to: {
        mailbox: MailboxId;
        thread: ThreadId;
      };
    }
  | {
      toggle_star: {
        thread: ThreadId;
      };
    }
  | {
      toggle_read: {
        thread: ThreadId;
      };
    }
  | {
      apply_label: {
        /**
         * Label text from the UI.
         */
        label: string;
        thread: ThreadId;
      };
    }
  | {
      search: {
        /**
         * The query string, including tokens such as `from:`.
         */
        query: string;
      };
    }
  | {
      switch_account: {
        account: AccountId;
      };
    }
  | "undo"
  | {
      download: {
        /**
         * File name from the mock. A content id replaces this when blobs exist.
         */
        name: string;
      };
    }
  | {
      sign_in: {
        /**
         * Account address.
         */
        email: string;
      };
    }
  | {
      sign_up: {
        /**
         * Account address.
         */
        email: string;
        /**
         * Display name.
         */
        name: string;
      };
    }
  | "sign_out"
  | {
      choose_plan: {
        /**
         * Plan key from the mock.
         */
        plan: string;
      };
    }
  | {
      set_language: {
        /**
         * Language code, or empty for English.
         */
        code: string;
      };
    }
  | {
      summarize: {
        thread: ThreadId;
      };
    };

export interface Contract {
  Envelope: Envelope;
  Event: Event;
  Submission: Submission;
}
/**
 * Headers and flags for one message, enough for a list and a reader chrome.
 *
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Envelope".
 */
export interface Envelope {
  /**
   * How many attachments the message has. Bytes live in the blob store.
   */
  attachment_count: number;
  /**
   * `Cc`.
   */
  cc: Address[];
  flags: Flags;
  from: Address;
  id: MessageId;
  /**
   * One-line preview. The full body is not part of the envelope.
   */
  snippet: string;
  /**
   * The mock's `stamp` (a display string, not a parsed timestamp).
   */
  stamp: string;
  /**
   * Subject. The mock stores it on the thread; a message still has one.
   */
  subject: string;
  thread: ThreadId;
  /**
   * `To`, split from the mock's comma-separated string.
   */
  to: Address[];
  transport: TransportSecurity;
}
/**
 * Someone a message is from, to or copied to.
 *
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Address".
 */
export interface Address {
  /**
   * Addr-spec (`ana@acme.io`).
   */
  email: string;
  /**
   * Display name when the header had one.
   */
  name?: string | null;
}
/**
 * Flags stored with a message. `seen` is the inverse of the list's unread
 * mark only for a one-message thread; a thread row keeps its own `unread`.
 *
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Flags".
 */
export interface Flags {
  /**
   * `\Answered`.
   */
  answered: boolean;
  /**
   * `\Deleted`. Distinct from the Trash mailbox.
   */
  deleted: boolean;
  /**
   * `\Draft`.
   */
  draft: boolean;
  /**
   * `\Flagged`. The UI calls this a star.
   */
  flagged: boolean;
  /**
   * Server keywords and labels (`snoozed`, a user label).
   */
  keywords: string[];
  /**
   * `\Seen`.
   */
  seen: boolean;
}
/**
 * One row in the thread list. Initials, tint and selection are UI state
 * and are not stored here.
 *
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "ThreadRow".
 */
export interface ThreadRow {
  account: AccountId;
  category: Category;
  /**
   * The conversation is a draft.
   */
  draft: boolean;
  /**
   * Starred.
   */
  flagged: boolean;
  from: Address;
  /**
   * At least one message has an attachment.
   */
  has_attachment: boolean;
  id: ThreadId;
  /**
   * Marked important.
   */
  important: boolean;
  /**
   * Label texts. Colours stay in the UI.
   */
  labels: string[];
  mailbox: MailboxId;
  /**
   * How many messages the conversation holds.
   */
  message_count: number;
  /**
   * Pinned to the top of the list.
   */
  pinned: boolean;
  /**
   * One-line preview.
   */
  snippet: string;
  /**
   * Hidden until a snooze wakes it.
   */
  snoozed: boolean;
  /**
   * Display stamp.
   */
  stamp: string;
  /**
   * Subject.
   */
  subject: string;
  /**
   * The row is unread. Not the same bit as one message's `\Seen`.
   */
  unread: boolean;
}
