<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Mailune.AppCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Mailune.Core/Mailune.Core.csproj" />
  </ItemGroup>
</Project>
